### PR TITLE
fix optional value based on public comments or not

### PR DESCRIPTION
**Pull request by melisabok**
- PC and assigned SAC shouldn't be mandatory if 'everyone' is present.

### CODE REVIEW

**Comment by melisabok** [comment]
@carlosmondra when everyone is present in the list of available readers we can not make the PCs mandatory. I don't think the API is taking everyone as a possible mandatory PCs.

**Comment by carlosmondra** [comment]
> @carlosmondra when everyone is present in the list of available readers we can not make the PCs mandatory. I don't think the API is taking everyone as a possible mandatory PCs.

I'm sorry, I don't understand what the issue is

**Comment by melisabok** [comment]
> I'm sorry, I don't understand what the issue is

if we want the PCs to be always readers of the comment and the invitation allows 'everyone' we don't need to force the PCs group to be in the readers list. This means that PCs shouldn't be `optional: False` because everyone can satisfy the condition of PCs reading the comments. My question is if the API is allowing to set everyone only when the PCs are optional false.

**Comment by carlosmondra** [comment]
> > I'm sorry, I don't understand what the issue is
> 
> if we want the PCs to be always readers of the comment and the invitation allows 'everyone' we don't need to force the PCs group to be in the readers list. This means that PCs shouldn't be `optional: False` because everyone can satisfy the condition of PCs reading the comments. My question is if the API is allowing to set everyone only when the PCs are optional false.

The API does not know whether a group is a subset of another. I think that could be very complicated. Unless I'm still misunderstanding the issue.

**Comment by melisabok** [comment]
> EDIT: Or do you want that everyone has a special behavior? Example: If everyone is selected the rest of the mandatory fields are not needed.

I'm not sure about this, I would like to keep the API simple.

**Review by carlosmondra — APPROVED** [review]

**Review by celestemartinez — APPROVED** [review]

**Pull request merged**
