### PR TITLE
ARR: Fix ethics review tests

### PR DESCRIPTION
**Pull request by haroldrubio**
This PR sets the ethics review stage to be active in the future instead of activating it as soon as the tests start. This fixes a bug where all submissions had an ethics review invitation created since the ethics review super invitation was active while the submission process functions ran.

Edited to add: I changed the test to start the ethics review stage from the beginning, to make sure no Ethics_Review invitatinos are created since no papers are flagged.

### CODE REVIEW

**Comment by celestemartinez** [comment]
I am a little bit confused about why ethics review invitations were created for all submissions, if it should be created only for flagged submissions? It shouldn't matter when the ethics review super invitation is active.

**Comment by melisabok** [comment]
@celestemartinez should we make that change in this PR? Only create invitations for `all_submissions` source.

**Comment by celestemartinez** [comment]
> @celestemartinez should we make that change in this PR? Only create invitations for `all_submissions` source.

yes, I can work on this

**Comment by celestemartinez** [comment]
This should be ready.

**Review by melisabok — APPROVED** [review]

**Review by celestemartinez — APPROVED** [review]

**Pull request merged**
