### PR TITLE
remove edge browser text

### PR DESCRIPTION
**Pull request by purujitgoyal**
Fix for openreview/openreview#12

### CODE REVIEW

**Comment by purujitgoyal** [comment]
Tests are passing on my local.

**Comment by celestemartinez** [comment]
Looks good, but I don't particularly like having just the link without any other text. I remember ARR complaining about this before and we changed the text to **Reviewer Browser**: https://openreview.net/group?id=aclweb.org/ACL/ARR/2021/October/Area_Chairs
If you think this is still not clear enough we can remove all text before the link

**Comment by purujitgoyal** [comment]
I think it works, but yes, **Reviewer Browser** does make it more clear than **Edge Browser**. The only issue I can think of is if we do change it to **Reviewer Browser**, we should make sure we do it everywhere else someone will come up with another issue.

**Comment by melisabok** [comment]
What about "Reviewer Assignment Browser"?

**Comment by melisabok** [comment]
@purujitgoyal instead of removing "Edge Browser" could you replace it with "Reviewer Assignment Browser"?

**Review by celestemartinez — APPROVED** [review]

**Review by melisabok — APPROVED** [review]

**Pull request merged**
