### PR TITLE
Fix/ Editor-in-Chief Console: link to new forum page

### PR DESCRIPTION
**Pull request by zbialecki**
Add option to EiC console to make all forum links go to new forum page.

Related to https://github.com/openreview/openreview-web/pull/899

### CODE REVIEW

**Comment by melisabok** [comment]
Is this PR still valid?

**Comment by melisabok** [comment]
does it mean the EICs will see the new forum page first? instead of having the option to switch using the banner?

**Comment by zbialecki** [comment]
Yes, this option changes the forum link in the tables to /forum-new. If you'd rather they continue being directed to the old forum we don't have to add the option on live.

**Comment by melisabok** [comment]
I would like to give them the option to choose if they want to go to the new forum. There are links to the forum everywhere and it can be confusing that one of the links go to the new one and the others don't.

**Comment by zbialecki** [comment]
OK, then I guess I'll close this PR for now.

**Pull request closed without merging**
