### PR TITLE
Feature/ Reviewer console - add download pdf button

### PR DESCRIPTION
**Pull request by xkopenreview**
this pr should add download pdf button to reviewer console of venues using webfield code
function-wise it should be the same as download pdf button in ac console

### CODE REVIEW

**Comment by melisabok** [comment]
Is it possible to show the button at the top of the table like the AC console?

Screen Shot 2023-01-12 at 10 07 05 AM

**Comment by melisabok** [comment]
did you push your recent changes @xkopenreview ?

**Review by melisabok — APPROVED** [review]

**Comment by melisabok** [comment]
I updated the CVPR reviewers console in the live site and it works ok!, Thanks @xkopenreview

**Review by haroldrubio — APPROVED** [review]

**Comment by melisabok** [comment]
Closing this PR given we are going to use the API 2 UI components from now on

**Pull request closed without merging**
