### PR TITLE
Adds SACs as AC group writers

### PR DESCRIPTION
**Pull request by purujitgoyal**

### CODE REVIEW

**Comment by melisabok** [comment]
@nlbahy please confirm but I think the assigned SAC needs to be writer of the assigned AC group, right? not the general AC group.

**Comment by nlbahy** [comment]
> @nlbahy please confirm but I think the assigned SAC needs to be writer of the assigned AC group, right? not the general AC group.

I have been fixing this by adding the overall SAC group as writers of the overall AC group, but technically this would allow SACs to edit the AC group. So it is probably safer to add each paper SAC as a writer of each paper AC.

**Comment by melisabok** [comment]
I'm nervous that SAC users can edit the AC group :/

**Comment by melisabok** [comment]
Fixed it in the API 2

**Pull request closed without merging**
