### PR TITLE
Fix/filter non-author tasks

### LINKED ISSUE #591: Author console: show tasks for authors only
It seems we are showing all the invitations when a user is an author and Ac/Reviewer:

This is Rene Vidal author console:

Screen Shot 2020-03-09 at 3 51 46 PM

### PR DESCRIPTION
**Pull request by zbialecki**
Standardize author, reviewer, and AC consoles to filter invitations in the same way.

Fixes #591

### CODE REVIEW

**Comment by zbialecki** [comment]
Yes, so was the area chair console, but it wasn't filtering tag invitation for some reason.

**Comment by melisabok** [comment]
I know this request is not  related to this issue but could you remove the 'Schedule' tab from the AC/Reviewers/Author console?

We are not really using them and it can be confusing for the users. 

May be in the future we can automatically create the schedule from the existent invitations.

**Comment by zbialecki** [comment]
Do you want to remove it entirely or just comment it out for now?

**Comment by melisabok** [comment]
comment it out for now.

**Pull request merged**
