### PR TITLE
Journal: only count assignments for current year

### PR DESCRIPTION
**Pull request by celestemartinez**
There is a shortage of available AEs. ~~The TMLR EICs recommended recalculation the assignment count of each AE and only consider assignments made in 2024.~~

~~I am checking when the assignment edge was created and count the assignment only if the assigment was made in the current year or if the assignment is still active.~~

Edit: I am archiving the ~300 assignments made in 2023, so the change described above is not necessary. 
**New change:** when looking at active assignments to compute `Local_Custom_Max_Papers`, only count assignments made in the last two months.

### CODE REVIEW

**Comment by celestemartinez** [comment]
Not finished yet, looks like TMLR wants another change as well.

**Review by carlosmondra — APPROVED** [review]
Nice

**Comment by celestemartinez** [comment]
@carlosmondra @enrubio last change! I added the inclusion date limit as an optional param in case other journal use this function as well.

**Comment by carlosmondra** [comment]
> @carlosmondra @enrubio last change! I added the inclusion date limit as an optional param in case other journal use this function as well.

I saw it! Looks good. Thanks!

**Pull request merged**
