### PR TITLE
Render a status table for author console

### PR DESCRIPTION
**Pull request by melisabok**
Similar to the AC console, currently it is hiding review and meta review status.

Zach, please check the css, the author names and details aren't correct.

### CODE REVIEW

**Comment by zbialecki** [comment]
I think the table looks good, and there aren't too many things I would change about the design, but I'm wondering if you plan on showing the review and meta review columns in the future? If not, I think we should remove that code from this webfield as a lot of it is unnecessary.

**Comment by melisabok** [comment]
I think it would be nice to show the status of the reviews to the authors. 

I have another problem here, I need to get the blind submissions of only the papers where the user is an author.

**Comment by melisabok** [comment]
I need to fix some CSS, author list and show details are not showed correctly:

Screen Shot 2020-02-14 at 6 27 35 PM

**Comment by zbialecki** [comment]
I'm reviewing this now, I can fix the CSS.

**Pull request merged**
