### PR TITLE
Decision stage: Update instructions

### PR DESCRIPTION
**Pull request by enrubio**
Update instructions to tell PCs to use "Accept" in the decision names.

### CODE REVIEW

**Comment by melisabok** [comment]
I'm not sure if this is going to help, PCs may not read the instructions. 

I would like to implement this: https://github.com/openreview/openreview-py/issues/1664

If this issue can take too much time, I suggest adding a preprocess validation that checks that are least one decision option has the work "Accept".

**Comment by racheljsmart** [comment]
> I'm not sure if this is going to help, PCs may not read the instructions.
> 
> I would like to implement this: #1664
> 
> If this issue can take too much time, I suggest adding a preprocess validation that checks that are least one decision option has the word "Accept".

Until that issue is implemented, I think adding a preprocess will help.

**Comment by melisabok** [comment]
@enrubio what should we do with this PR?

**Comment by enrubio** [comment]
I can add a preprocess here that checks if there's at least one "Accept" option. I still think we should update the instructions.

**Comment by melisabok** [comment]
What about fixing the issue https://github.com/openreview/openreview-py/issues/1664 directly.

**Comment by enrubio** [comment]
Okay, so no preprocess then. I can work on that issue. We can just close this PR in that case.

**Pull request closed without merging**
