### PR TITLE
Update setup.py to require Python 3.9

### PR DESCRIPTION
**Pull request by emily-grabowski**
Add requirement for Python 3.9 in setup.py

### CODE REVIEW

**Comment by carlosmondra** [comment]
Is it possible to make the requirement accept versions 3.8 - 3.10?
circleci tests run with version 3.10 and my local installation works with 3.8. I suppose several users use these versions. I would also check if it works with versions 3.6 and 3.7 even if they are going to be deprecated soon.

An alternative would be to make these checks in circleci. We could add a job that tries to install openreview-py with every version that we want to support.

**Comment by melisabok** [comment]
CircleCI is already failing because of this change so if Python 3.10 works then we accept this version too.

**Comment by emily-grabowski** [comment]
I can change this to include a range of Python versions that are accepted - I think the function was removed in Python 3.12, so anything < Python 3.12 should work

**Comment by emily-grabowski** [comment]
I updated setup.py to require <Python 3.12 and tested it on Python 3.8-3.12

**Review by melisabok — APPROVED** [review]

**Review by carlosmondra — APPROVED** [review]

**Pull request merged**
