### PR TITLE
Fix/iclr submission stage

### PR DESCRIPTION
**Pull request by melisabok**

### CODE REVIEW

**Comment by melisabok** [comment]
@celestemartinez could you take a look at these changes and we can discuss them on a video call.

**Comment by celestemartinez** [comment]
Just one question, are we adding a field for 'second_due_date' to the request form, or how are we setting this date?

**Comment by melisabok** [comment]
> Just one question, are we adding a field for 'second_due_date' to the request form, or how are we setting this date?

I think we discussed that we shouldn't add it because most of the venues don't have a second deadline. I could add this field to the ICLR request form only, or we can set the SubmissionStage from python.

**Review by celestemartinez — APPROVED** [review]
Looks good!

**Pull request merged**
