### PR TITLE
Replace Object.values with lodash equivalent

### PR DESCRIPTION
**Pull request by zbialecki**
Apparently Object.values was not included in the current polyfill.

### CODE REVIEW

**Comment by xkopenreview** [comment]
tried adding bundled corejs to vendor (didn't remove existing polyfill) and seems that the mathjax error is gone.

**Comment by zbialecki** [comment]
If this PR is merged https://github.com/openreview/openreview/pull/2062 then these changes won't really be necessary.

**Comment by melisabok** [comment]
I think we can close this issue, right?

**Comment by zbialecki** [comment]
Yes, agreed.

**Pull request closed without merging**
