### PR TITLE
Add max note count as option for the bid stage

### PR DESCRIPTION
**Pull request by carlosmondra**

### CODE REVIEW

**Comment by melisabok** [comment]
You could the max_count in the venue request form so the PCs can decide if they want to limit it or not:

https://github.com/openreview/openreview-py/blob/master/openreview/venue_request/venue_request.py#L63

**Comment by carlosmondra** [comment]
I realized that this does not work and I have not had the time to really fix it.

**Comment by melisabok** [comment]
Ok, I can assign it to somewhere else. 

Sometimes venues ask for this.

**Comment by melisabok** [comment]
@carlosmondra , can @xkopenreview add this feature to the new react bidding console? should we wait until we have a first version and add this later?

**Comment by carlosmondra** [comment]
> @carlosmondra , can @xkopenreview add this feature to the new react bidding console? should we wait until we have a first version and add this later?

I think it's fine if he can add it. I realized that my approach in this PR was wrong, he would need to fix that first. If it's too troublesome, maybe we can wait until later to implement it.

**Comment by xkopenreview** [comment]
what's the rational of limiting the number of papers retrieved?

**Comment by melisabok** [comment]
>what's the rationale of limiting the number of papers retrieved?

Some PCs don't want reviewers to see more than the top N papers. They haven't request this lately so I suggest to close this PR, agree?

**Comment by carlosmondra** [comment]
Yes, we need to rethink the approach anyway.

**Pull request closed without merging**
