### PR TITLE
Support type 'profile' for authorids

### PR DESCRIPTION
**Pull request by melisabok**
It depends on https://github.com/openreview/openreview-api/pull/380

This PR is ready to be merged.

### CODE REVIEW

**Comment by xkopenreview** [comment]
currently type group and group[] are rendered as profile search widget
for this to continue working i will need to change that check to profile and profile[]

does this change mean that type of a field can't be group and group[] any more?
or group and group[] should still be rendered as profile search widget or some other widget?

**Comment by melisabok** [comment]
it can be both, group or profile. Having profile helps the API to validate the authorids are valid profileids or emails. 

This is done to fix the issue when ECCV submitted the papers and use a fake tilde id as authorids. 

I do think the UI could validate both types.

**Comment by xkopenreview** [comment]
so both profile and group will render as profile search widget right?

**Comment by melisabok** [comment]
> so both profile and group will render as profile search widget right?

Yes.

**Pull request merged**
